matrix:
  include:
    - language: java
      jdk:
        - oraclejdk8
        - openjdk8
      os:
        - linux
    - language: node_js
      node_js:
        - "8"
        - "7"
        - "iojs"
      before_script:
        - cd customer_frontend/
